//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYDB.Infrastructure.Entity
{
    public  class UserRecharge:BaseEntity
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long UserId { get; set; }
        public decimal Amount { get; set; }
        public PayState State { get; set; }
        public PayType PayType { get; set; }
        public string SerialNumber { get; set; }
    }
}
